GET http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxvZ2luVGVzdCIsImlkIjoiNjRlM2I2ZGMwMzM5MmJmMDBmN2JjM2MzIiwiaWF0IjoxNjkyNjQ2ODI3fQ.9WFooHkplMwmD4hY2uuTJGwfSehgsOksEegJ0bEMDuo